[build]
command = "./scripts/build.sh"
publish = "_site"

[build.environment]
RUBY_VERSION = "2.6.2"

[[redirects]]
  from = "/"
  to = "/WAI/ARIA/APG/"

[dev]
# NB on win64 (cmd or bash shells) --live reload is broken - s/-w --livereload/--no-watch
command = "bundle exec jekyll serve -w --livereload --trace --config _config.yml,_config_staging.yml"
