[build]
# NB rm -rf typically applies to UNIX environments which this Netlify deploy works; a temporary solution to while figuring why .gitmodule updates are causing deploy issues unless cache is reset
command = "rm -rf .git/modules .git/modules/* .git/index .git/.gitmodules .netlify .cache node_modules build dist out && git submodule update --init --remote && bundle exec jekyll build --config '_config.yml,_config_staging.yml'"
publish = "_site"

[build.environment]
RUBY_VERSION = "3.3.3"

[[redirects]]
  from = "/"
  to = "/ARIA/apg/"

[dev]
# NB on win64 (cmd or bash shells) --live reload is broken - s/-w --livereload/--no-watch
command = "bundle exec jekyll serve -w --livereload --trace --config _config.yml,_config_staging.yml"
