[build]
command = "git submodule update --init --remote && bundle update wai-website-theme --conservative && bundle update wai-website-plugin --conservative && bundle exec jekyll build --config '_config.yml,_config_staging.yml'"
publish = "_site"

[build.environment]
RUBY_VERSION = "3.4.8"

[[redirects]]
  from = "/"
  to = "/ARIA/apg/"

[dev]
# NB on win64 (cmd or bash shells) --live reload is broken - s/-w --livereload/--no-watch
command = "bundle exec jekyll serve -w --livereload --trace --config _config.yml,_config_staging.yml"
